#!/usr/bin/env bash

#definevariables

KEY_NAME= "school"
KEY_BITS= 4096
PASSPHRASE= "betty"

# Creates RSA key pair
openssl genrsa -aes256 -passout pass:"$PASSPHRASE" -out "$KEY_NAME".key "$KEY_BITS"

# Generate corresponding public key
openssl rsa -in "$KEY_NAME".key -pubout -out "$KEY_NAME".pub -passin pass:"$PASSPHRASE"

# Output success message
echo "RSA key pair generated successfully:"
echo "Private key: $KEY_NAME.key"
echo "Public key: $KEY_NAME.pub"
